//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Handles the `MenuSectionDeletedEvent` which occurs when a new menusection is deleted.
//       This event handler can be extended to trigger additional actions, such as 
//       sending notifications or updating other systems.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Domain.Events;

namespace CleanArchitecture.Blazor.Application.Features.MenuSections.EventHandlers;

    public class MenuSectionDeletedEventHandler : INotificationHandler<MenuSectionDeletedEvent>
    {
        private readonly ILogger<MenuSectionDeletedEventHandler> _logger;

        public MenuSectionDeletedEventHandler(
            ILogger<MenuSectionDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(MenuSectionDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
