//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for MenuSectionSubItem-related data. This includes creating unique cache keys for 
//       various menusectionsubitem queries (such as getting all menusectionsubitems, menusectionsubitems by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Caching;
/// <summary>
/// Static class for managing cache keys and expiration for MenuSectionSubItem-related data.
/// </summary>
public static class MenuSectionSubItemCacheKey
{
    public const string GetAllCacheKey = "all-MenuSectionSubItems";
    public static string GetPaginationCacheKey(string parameters) {
        return $"MenuSectionSubItemCacheKey:MenuSectionSubItemsWithPaginationQuery,{parameters}";
    }
    public static string GetExportCacheKey(string parameters) {
        return $"MenuSectionSubItemCacheKey:ExportCacheKey,{parameters}";
    }
    public static string GetByNameCacheKey(string parameters) {
        return $"MenuSectionSubItemCacheKey:GetByNameCacheKey,{parameters}";
    }
    public static string GetByIdCacheKey(string parameters) {
        return $"MenuSectionSubItemCacheKey:GetByIdCacheKey,{parameters}";
    }
    public static IEnumerable<string>? Tags => new string[] { "menusectionsubitem" };
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}

