//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Handles the `MenuSectionItemCreatedEvent` which occurs when a new menusectionitem is created.
//       This event handler can be extended to trigger additional actions, such as 
//       sending notifications or updating other systems.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Domain.Events.MenuSectionItems;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.EventHandlers;

public class MenuSectionItemCreatedEventHandler : INotificationHandler<MenuSectionItemCreatedEvent>
{
        private readonly ILogger<MenuSectionItemCreatedEventHandler> _logger;

        public MenuSectionItemCreatedEventHandler(
            ILogger<MenuSectionItemCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(MenuSectionItemCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
