//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Handles the `MenuSectionItemDeletedEvent` which occurs when a new menusectionitem is deleted.
//       This event handler can be extended to trigger additional actions, such as 
//       sending notifications or updating other systems.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Domain.Events.MenuSectionItems;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.EventHandlers;

    public class MenuSectionItemDeletedEventHandler : INotificationHandler<MenuSectionSubItemDeletedEvent>
    {
        private readonly ILogger<MenuSectionItemDeletedEventHandler> _logger;

        public MenuSectionItemDeletedEventHandler(
            ILogger<MenuSectionItemDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(MenuSectionSubItemDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
