//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the LookupDetail entity 
//       used within the CleanArchitecture.Blazor application. The LookupDetailDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/lookupdetail
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `LookupDetailDto` class is used to represent lookupdetail data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing lookupdetail information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

using CleanArchitecture.Blazor.Application.Features.Lookups.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.LookupDetails.DTOs;

[Description("LookupDetails")]
public class LookupDetailDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Lookup id")]
    public int LookupId {get;set;}
    public string LookupName { get; set; }
    [Description("Code")]
    public string? Code {get;set;} 
    [Description("Name")]
    public string Name {get;set;} 
    [Description("Name bn")]
    public string? NameBN {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Lookup detail id")]
    public int? LookupDetailId {get;set;} 
    [Description("Is active")]
    public bool IsActive {get;set;}
    [Description("Lookup")]
    public LookupDto Lookup { get; set; } = new();


}

