//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for MenuSectionItem-related data. This includes creating unique cache keys for 
//       various menusectionitem queries (such as getting all menusectionitems, menusectionitems by ID, etc.), 
//       managing the cache expiration tokens to control cache validity, and providing a 
//       mechanism to refresh cached data in a thread-safe manner.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Caching;
/// <summary>
/// Static class for managing cache keys and expiration for MenuSectionItem-related data.
/// </summary>
public static class MenuSectionItemCacheKey
{
    public const string GetAllCacheKey = "all-MenuSectionItems";
    public static string GetPaginationCacheKey(string parameters) {
        return $"MenuSectionItemCacheKey:MenuSectionItemsWithPaginationQuery,{parameters}";
    }
    public static string GetExportCacheKey(string parameters) {
        return $"MenuSectionItemCacheKey:ExportCacheKey,{parameters}";
    }
    public static string GetByNameCacheKey(string parameters) {
        return $"MenuSectionItemCacheKey:GetByNameCacheKey,{parameters}";
    }
    public static string GetByIdCacheKey(string parameters) {
        return $"MenuSectionItemCacheKey:GetByIdCacheKey,{parameters}";
    }
    public static IEnumerable<string>? Tags => new string[] { "menusectionitem" };
    public static void Refresh()
    {
        FusionCacheFactory.RemoveByTags(Tags);
    }
}

