//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines a query for retrieving menusections with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.MenuSections.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSections.Caching;
using CleanArchitecture.Blazor.Application.Features.MenuSections.Mappers;
using CleanArchitecture.Blazor.Application.Features.MenuSections.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.MenuSections.Queries.Pagination;

public class MenuSectionsWithPaginationQuery : MenuSectionAdvancedFilter, IRequest<PaginatedData<MenuSectionDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public MenuSectionAdvancedSpecification Specification => new MenuSectionAdvancedSpecification(this);
}
    
public class MenuSectionsWithPaginationQueryHandler :
         IRequestHandler<MenuSectionsWithPaginationQuery, PaginatedData<MenuSectionDto>>
{
        private readonly IApplicationDbContext _context;

        public MenuSectionsWithPaginationQueryHandler(
            IApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<PaginatedData<MenuSectionDto>> Handle(MenuSectionsWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.MenuSections.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync(request.Specification, 
                                                                                request.PageNumber, 
                                                                                request.PageSize, 
                                                                                MenuSectionMapper.ToDto, 
                                                                                cancellationToken);
            return data;
        }
}