//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Defines a query to retrieve a lookupdetail by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same lookupdetail.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.LookupDetails.DTOs;
using CleanArchitecture.Blazor.Application.Features.LookupDetails.Caching;
using CleanArchitecture.Blazor.Application.Features.LookupDetails.Mappers;
using CleanArchitecture.Blazor.Application.Features.LookupDetails.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.LookupDetails.Queries.GetById;

public class GetLookupDetailByIdQuery : IRequest<Result<LookupDetailDto>>
{
   public required int Id { get; set; }
}

public class GetLookupDetailByIdQueryHandler :
     IRequestHandler<GetLookupDetailByIdQuery, Result<LookupDetailDto>>
{
    private readonly IApplicationDbContext _context;

    public GetLookupDetailByIdQueryHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<LookupDetailDto>> Handle(GetLookupDetailByIdQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.LookupDetails.ApplySpecification(new LookupDetailByIdSpecification(request.Id))
                                                .ProjectTo()
                                                .FirstAsync(cancellationToken);
        return await Result<LookupDetailDto>.SuccessAsync(data);
    }
}
