//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Represents a domain event that occurs when a new menusection is updated.
//       Used to signal other parts of the system that a new menusection has been updated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events.MenuSectionItems;


    public class MenuSectionSubItemUpdatedEvent : DomainEvent
    {
        public MenuSectionSubItemUpdatedEvent(MenuSectionSubItem item)
        {
            Item = item;
        }

        public MenuSectionSubItem Item { get; }
    }

