//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       This file defines the validation rules for the AddEditMenuSectionCommand 
//       used to add or edit MenuSection entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/menusection
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditMenuSectionCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.MenuSections.Commands.AddEdit;

public class AddEditMenuSectionCommandValidator : AbstractValidator<AddEditMenuSectionCommand>
{
    public AddEditMenuSectionCommandValidator()
    {
                RuleFor(v => v.Title).MaximumLength(255); 

     }

}

