//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       This file defines the command, handler, and associated logic for importing 
//       lookups from an Excel file into the CleanArchitecture.Blazor application. 
//       The import process supports validating data and ensuring no duplicates are 
//       inserted. Additionally, a command for creating a lookup template file is provided 
//       to facilitate bulk data entry for end users.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/lookup
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// - Use `ImportLookupsCommand` to import lookups from an Excel file, ensuring proper validation
//   and avoiding duplicates.
// - Use `CreateLookupsTemplateCommand` to generate an Excel template for entering lookup data 
//   that can be later imported using the import command.

using CleanArchitecture.Blazor.Application.Features.Lookups.DTOs;
using CleanArchitecture.Blazor.Application.Features.Lookups.Caching;
using CleanArchitecture.Blazor.Application.Features.Lookups.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.Lookups.Commands.Import;

    public class ImportLookupsCommand: IRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public ImportLookupsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateLookupsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportLookupsCommandHandler : 
                 IRequestHandler<CreateLookupsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportLookupsCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        private readonly IStringLocalizer<ImportLookupsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly LookupDto _dto = new();

        public ImportLookupsCommandHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ImportLookupsCommandHandler> localizer)
        {
            _context = context;
            _localizer = localizer;
            _excelService = excelService;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportLookupsCommand request, CancellationToken cancellationToken)
        {

           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, LookupDto, object?>>
            {
                { _localizer[_dto.GetMemberDescription(x=>x.Code)], (row, item) => item.Code = row[_localizer[_dto.GetMemberDescription(x=>x.Code)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Name)], (row, item) => item.Name = row[_localizer[_dto.GetMemberDescription(x=>x.Name)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.NameBN)], (row, item) => item.NameBN = row[_localizer[_dto.GetMemberDescription(x=>x.NameBN)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.ParentId)], (row, item) => item.ParentId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.ParentId)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.DevCode)], (row, item) => item.DevCode = Enum.Parse<DevCode>(row[_localizer[_dto.GetMemberDescription(x=>x.DevCode)]].ToString()) }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await _context.Lookups.AnyAsync(x => x.Name == dto.Name, cancellationToken);
                    if (!exists)
                    {
                        var item = LookupMapper.FromDto(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new LookupCreatedEvent(item));
                        await _context.Lookups.AddAsync(item, cancellationToken);
                    }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateLookupsTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportLookupsCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.Code)], 
_localizer[_dto.GetMemberDescription(x=>x.Name)], 
_localizer[_dto.GetMemberDescription(x=>x.NameBN)], 
_localizer[_dto.GetMemberDescription(x=>x.ParentId)], 
_localizer[_dto.GetMemberDescription(x=>x.IsActive)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

