//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines a specification for filtering a MenuSection entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.MenuSections.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering MenuSections by their ID.
/// </summary>
public class MenuSectionByIdSpecification : Specification<MenuSection>
{
    public MenuSectionByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}