//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Configures the properties and behaviors for the `Lookup` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Domain.Entities.Common;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class LookupConfiguration : IEntityTypeConfiguration<Lookup>
{
    public void Configure(EntityTypeBuilder<Lookup> builder)
    {
            builder.Property(x => x.Code).HasMaxLength(255); 
    builder.HasIndex(x => x.Name); 
    builder.Property(x => x.Name).HasMaxLength(50).IsRequired(); 
    builder.Property(x => x.NameBN).HasMaxLength(255); 
    builder.HasIndex(x => x.DevCode); 
    builder.Property(t => t.DevCode).HasConversion<string>().HasMaxLength(50); 

        builder.Ignore(e => e.DomainEvents);
    }
}


