//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       Configures the properties and behaviors for the `MenuSectionSubItem` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class MenuSectionSubItemConfiguration : IEntityTypeConfiguration<MenuSectionSubItem>
{
    public void Configure(EntityTypeBuilder<MenuSectionSubItem> builder)
    {
            builder.Property(x => x.Title).HasMaxLength(255); 
    builder.Property(x => x.Href).HasMaxLength(255); 
    builder.HasIndex(x => x.PageStatus); 
    builder.Property(t => t.PageStatus).HasConversion<string>().HasMaxLength(50); 
    builder.Property(x => x.Target).HasMaxLength(255); 
    builder.HasOne(x => x.MenuSectionItem).WithMany().HasForeignKey(x => x.MenuSectionItemId); 

        builder.Ignore(e => e.DomainEvents);
    }
}


