//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines mapping methods between `MenuSection` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting menusection data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.MenuSections.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.MenuSections.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.MenuSections.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class MenuSectionMapper
{
    public static partial MenuSectionDto ToDto(MenuSection source);
    public static partial MenuSection FromDto(MenuSectionDto dto);
    public static partial MenuSection FromEditCommand(AddEditMenuSectionCommand command);
    public static partial AddEditMenuSectionCommand CloneFromDto(MenuSectionDto dto);
    public static partial AddEditMenuSectionCommand ToEditCommand(MenuSectionDto dto);
    public static partial void ApplyChangesFrom(AddEditMenuSectionCommand source, MenuSection target);
    public static partial IQueryable<MenuSectionDto> ProjectTo(this IQueryable<MenuSection> q);
}

