//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       Defines mapping methods between `MenuSectionSubItem` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting menusectionsubitem data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class MenuSectionSubItemMapper
{
    public static partial MenuSectionSubItemDto ToDto(MenuSectionSubItem source);
    public static partial MenuSectionSubItem FromDto(MenuSectionSubItemDto dto);
    public static partial MenuSectionSubItem FromEditCommand(AddEditMenuSectionSubItemCommand command);
    public static partial AddEditMenuSectionSubItemCommand CloneFromDto(MenuSectionSubItemDto dto);
    public static partial AddEditMenuSectionSubItemCommand ToEditCommand(MenuSectionSubItemDto dto);
    public static partial void ApplyChangesFrom(AddEditMenuSectionSubItemCommand source, MenuSectionSubItem target);
    public static partial IQueryable<MenuSectionSubItemDto> ProjectTo(this IQueryable<MenuSectionSubItem> q);
}

