//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       Handles the `MenuSectionSubItemUpdatedEvent` which occurs when a new menusectionsubitem is updated.
//       This event handler can be extended to trigger additional actions, such as 
//       sending notifications or updating other systems.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Domain.Events.MenuSectionItems;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.EventHandlers;

    public class MenuSectionSubItemUpdatedEventHandler : INotificationHandler<MenuSectionSubItemUpdatedEvent>
    {
        private readonly ILogger<MenuSectionSubItemUpdatedEventHandler> _logger;

        public MenuSectionSubItemUpdatedEventHandler(
            ILogger<MenuSectionSubItemUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(MenuSectionSubItemUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
