//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       This file defines the command for adding or editing a menusectionsubitem entity,
//       including validation and mapping operations. It handles domain events
//       and cache invalidation for updated or newly created menusectionsubitem.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/menusectionsubitem
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to add a new menusectionsubitem or edit an existing one.
// It handles caching logic and domain event raising automatically.


using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Caching;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Mappers;
using CleanArchitecture.Blazor.Domain.Events.MenuSectionItems;
using CleanArchitecture.Blazor.Domain.Events.MenuSectionSubItems;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Commands.AddEdit;

public class AddEditMenuSectionSubItemCommand : IRequest<Result<int>>
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("Menu section item id")]
    public int MenuSectionItemId { get; set; }
    [Description("Title")]
    public string? Title { get; set; }
    [Description("Href")]
    public string? Href { get; set; }
    [Description("Roles")]
    public string[] Roles { get; set; }
    [Description("Page status")]
    public PageStatus? PageStatus { get; set; }
    [Description("Target")]
    public string? Target { get; set; }
    [Description("Serial No")]
    public int SerialNo { get; set; }
    [Description("Menu section item")]
    public MenuSectionItemDto MenuSectionItem { get; set; }

}

public class AddEditMenuSectionSubItemCommandHandler : IRequestHandler<AddEditMenuSectionSubItemCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    public AddEditMenuSectionSubItemCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(AddEditMenuSectionSubItemCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            var item = await _context.MenuSectionSubItems.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"MenuSectionSubItem with id: [{request.Id}] not found.");
            }
            MenuSectionSubItemMapper.ApplyChangesFrom(request, item);
            // raise a update domain event
            item.AddDomainEvent(new MenuSectionSubItemUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = MenuSectionSubItemMapper.FromEditCommand(request);
            // raise a create domain event
            item.AddDomainEvent(new MenuSectionSubItemCreatedEvent(item));
            _context.MenuSectionSubItems.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }

    }
}

