//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       This file defines the command, handler, and associated logic for importing 
//       menusectionitems from an Excel file into the CleanArchitecture.Blazor application. 
//       The import process supports validating data and ensuring no duplicates are 
//       inserted. Additionally, a command for creating a menusectionitem template file is provided 
//       to facilitate bulk data entry for end users.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/menusectionitem
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// - Use `ImportMenuSectionItemsCommand` to import menusectionitems from an Excel file, ensuring proper validation
//   and avoiding duplicates.
// - Use `CreateMenuSectionItemsTemplateCommand` to generate an Excel template for entering menusectionitem data 
//   that can be later imported using the import command.

using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Caching;
using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Commands.Import;

    public class ImportMenuSectionItemsCommand: IRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => MenuSectionItemCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => MenuSectionItemCacheKey.Tags;
        public ImportMenuSectionItemsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateMenuSectionItemsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportMenuSectionItemsCommandHandler : 
                 IRequestHandler<CreateMenuSectionItemsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportMenuSectionItemsCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        private readonly IStringLocalizer<ImportMenuSectionItemsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly MenuSectionItemDto _dto = new();

        public ImportMenuSectionItemsCommandHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ImportMenuSectionItemsCommandHandler> localizer)
        {
            _context = context;
            _localizer = localizer;
            _excelService = excelService;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportMenuSectionItemsCommand request, CancellationToken cancellationToken)
        {

           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, MenuSectionItemDto, object?>>
            {
                { _localizer[_dto.GetMemberDescription(x=>x.MenuSectionId)], (row, item) => item.MenuSectionId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.MenuSectionId)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Title)], (row, item) => item.Title = row[_localizer[_dto.GetMemberDescription(x=>x.Title)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Icon)], (row, item) => item.Icon = row[_localizer[_dto.GetMemberDescription(x=>x.Icon)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Href)], (row, item) => item.Href = row[_localizer[_dto.GetMemberDescription(x=>x.Href)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Target)], (row, item) => item.Target = row[_localizer[_dto.GetMemberDescription(x=>x.Target)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.PageStatus)], (row, item) => item.PageStatus = Enum.Parse<PageStatus>(row[_localizer[_dto.GetMemberDescription(x=>x.PageStatus)]].ToString()) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.IsParent)], (row, item) => item.IsParent =Convert.ToBoolean(row[_localizer[_dto.GetMemberDescription(x=>x.IsParent)]]) }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await _context.MenuSectionItems.AnyAsync(x => x.Title == dto.Title, cancellationToken);
                    if (!exists)
                    {
                        var item = MenuSectionItemMapper.FromDto(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new MenuSectionItemCreatedEvent(item));
                        await _context.MenuSectionItems.AddAsync(item, cancellationToken);
                    }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateMenuSectionItemsTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportMenuSectionItemsCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.MenuSectionId)], 
_localizer[_dto.GetMemberDescription(x=>x.Title)], 
_localizer[_dto.GetMemberDescription(x=>x.Icon)], 
_localizer[_dto.GetMemberDescription(x=>x.Href)], 
_localizer[_dto.GetMemberDescription(x=>x.Target)], 
_localizer[_dto.GetMemberDescription(x=>x.IsParent)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

