//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Defines permission constants for lookup-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("Lookup Permissions")]
    [Description("Set permissions for lookup operations.")]
    public static class Lookups
    {
        [Description("Allows viewing lookup details.")]
        public const string View = "Permissions.Lookups.View";
        [Description("Allows creating lookup details.")]
        public const string Create = "Permissions.Lookups.Create";
        [Description("Allows editing lookup details.")]
        public const string Edit = "Permissions.Lookups.Edit";
        [Description("Allows deleting lookup details.")]
        public const string Delete = "Permissions.Lookups.Delete";
        [Description("Allows printing lookup details.")]
        public const string Print = "Permissions.Lookups.Print";
        [Description("Allows searching lookup details.")]
        public const string Search = "Permissions.Lookups.Search";
        [Description("Allows exporting lookup details.")]
        public const string Export = "Permissions.Lookups.Export";
        [Description("Allows importing lookup details.")]
        public const string Import = "Permissions.Lookups.Import";
    }
}

