//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Defines permission constants for lookupdetail-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("LookupDetail Permissions")]
    [Description("Set permissions for lookupdetail operations.")]
    public static class LookupDetails
    {
        [Description("Allows viewing lookupdetail details.")]
        public const string View = "Permissions.LookupDetails.View";
        [Description("Allows creating lookupdetail details.")]
        public const string Create = "Permissions.LookupDetails.Create";
        [Description("Allows editing lookupdetail details.")]
        public const string Edit = "Permissions.LookupDetails.Edit";
        [Description("Allows deleting lookupdetail details.")]
        public const string Delete = "Permissions.LookupDetails.Delete";
        [Description("Allows printing lookupdetail details.")]
        public const string Print = "Permissions.LookupDetails.Print";
        [Description("Allows searching lookupdetail details.")]
        public const string Search = "Permissions.LookupDetails.Search";
        [Description("Allows exporting lookupdetail details.")]
        public const string Export = "Permissions.LookupDetails.Export";
        [Description("Allows importing lookupdetail details.")]
        public const string Import = "Permissions.LookupDetails.Import";
    }
}

