//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines permission constants for menusection-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("MenuSection Permissions")]
    [Description("Set permissions for menusection operations.")]
    public static class MenuSections
    {
        [Description("Allows viewing menusection details.")]
        public const string View = "Permissions.MenuSections.View";
        [Description("Allows creating menusection details.")]
        public const string Create = "Permissions.MenuSections.Create";
        [Description("Allows editing menusection details.")]
        public const string Edit = "Permissions.MenuSections.Edit";
        [Description("Allows deleting menusection details.")]
        public const string Delete = "Permissions.MenuSections.Delete";
        [Description("Allows printing menusection details.")]
        public const string Print = "Permissions.MenuSections.Print";
        [Description("Allows searching menusection details.")]
        public const string Search = "Permissions.MenuSections.Search";
        [Description("Allows exporting menusection details.")]
        public const string Export = "Permissions.MenuSections.Export";
        [Description("Allows importing menusection details.")]
        public const string Import = "Permissions.MenuSections.Import";
    }
}

