//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines permission constants for menusectionitem-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("MenuSectionItem Permissions")]
    [Description("Set permissions for menusectionitem operations.")]
    public static class MenuSectionItems
    {
        [Description("Allows viewing menusectionitem details.")]
        public const string View = "Permissions.MenuSectionItems.View";
        [Description("Allows creating menusectionitem details.")]
        public const string Create = "Permissions.MenuSectionItems.Create";
        [Description("Allows editing menusectionitem details.")]
        public const string Edit = "Permissions.MenuSectionItems.Edit";
        [Description("Allows deleting menusectionitem details.")]
        public const string Delete = "Permissions.MenuSectionItems.Delete";
        [Description("Allows printing menusectionitem details.")]
        public const string Print = "Permissions.MenuSectionItems.Print";
        [Description("Allows searching menusectionitem details.")]
        public const string Search = "Permissions.MenuSectionItems.Search";
        [Description("Allows exporting menusectionitem details.")]
        public const string Export = "Permissions.MenuSectionItems.Export";
        [Description("Allows importing menusectionitem details.")]
        public const string Import = "Permissions.MenuSectionItems.Import";
    }
}

