//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       Defines permission constants for menusectionsubitem-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("MenuSectionSubItem Permissions")]
    [Description("Set permissions for menusectionsubitem operations.")]
    public static class MenuSectionSubItems
    {
        [Description("Allows viewing menusectionsubitem details.")]
        public const string View = "Permissions.MenuSectionSubItems.View";
        [Description("Allows creating menusectionsubitem details.")]
        public const string Create = "Permissions.MenuSectionSubItems.Create";
        [Description("Allows editing menusectionsubitem details.")]
        public const string Edit = "Permissions.MenuSectionSubItems.Edit";
        [Description("Allows deleting menusectionsubitem details.")]
        public const string Delete = "Permissions.MenuSectionSubItems.Delete";
        [Description("Allows printing menusectionsubitem details.")]
        public const string Print = "Permissions.MenuSectionSubItems.Print";
        [Description("Allows searching menusectionsubitem details.")]
        public const string Search = "Permissions.MenuSectionSubItems.Search";
        [Description("Allows exporting menusectionsubitem details.")]
        public const string Export = "Permissions.MenuSectionSubItems.Export";
        [Description("Allows importing menusectionsubitem details.")]
        public const string Import = "Permissions.MenuSectionSubItems.Import";
    }
}

