//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Defines a query to retrieve all lookups from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Lookups.DTOs;
using CleanArchitecture.Blazor.Application.Features.Lookups.Mappers;
using CleanArchitecture.Blazor.Application.Features.Lookups.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Lookups.Queries.GetAll;

public class GetAllLookupsQuery : IRequest<IEnumerable<LookupDto>>
{
}

public class GetAllLookupsQueryHandler :
     IRequestHandler<GetAllLookupsQuery, IEnumerable<LookupDto>>
{
    private readonly IApplicationDbContext _context;

    public GetAllLookupsQueryHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<LookupDto>> Handle(GetAllLookupsQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.Lookups.ProjectTo()
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


