//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines mapping methods between `MenuSectionItem` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting menusectionitem data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class MenuSectionItemMapper
{
    public static partial MenuSectionItemDto ToDto(MenuSectionItem source);
    public static partial MenuSectionItem FromDto(MenuSectionItemDto dto);
    public static partial MenuSectionItem FromEditCommand(AddEditMenuSectionItemCommand command);
    public static partial AddEditMenuSectionItemCommand CloneFromDto(MenuSectionItemDto dto);
    public static partial void ApplyChangesFrom(AddEditMenuSectionItemCommand source, MenuSectionItem target);
    public static partial AddEditMenuSectionItemCommand ToEditCommand(MenuSectionItemDto dto);
    public static partial IQueryable<MenuSectionItemDto> ProjectTo(this IQueryable<MenuSectionItem> q);
}

