//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the Lookup entity 
//       used within the CleanArchitecture.Blazor application. The LookupDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/lookup
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `LookupDto` class is used to represent lookup data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing lookup information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

namespace CleanArchitecture.Blazor.Application.Features.Lookups.DTOs;

[Description("Lookups")]
public class LookupDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Code")]
    public string? Code {get;set;} 
    [Description("Name")]
    public string Name {get;set;} 
    [Description("Name Bangla")]
    public string? NameBN {get;set;} 
    [Description("ParentId")]
    public int? ParentId {get;set;}
    [Description("Parent")]
    public string ParentName { get; set; }

    [Description("Status")]
    public bool IsActive { get; set; }
    [Description("StatusName")]
    public string StatusName { get; set; }
    [Description("Dev code")]
    public DevCode? DevCode {get;set;}

    [Description("Created")]
    public DateTime? Created { get; set; }
}

