//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the MenuSectionItem entity 
//       used within the CleanArchitecture.Blazor application. The MenuSectionItemDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/menusectionitem
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `MenuSectionItemDto` class is used to represent menusectionitem data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing menusectionitem information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

using CleanArchitecture.Blazor.Application.Features.MenuSections.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.DTOs;

[Description("MenuSectionItems")]
public class MenuSectionItemDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Menu section id")]
    public int MenuSectionId {get;set;} 
    [Description("Title")]
    public string? Title {get;set;} 
    [Description("Icon")]
    public string? Icon {get;set;} 
    [Description("Href")]
    public string? Href {get;set;} 
    [Description("Target")]
    public string? Target {get;set;} 
    [Description("Roles")]
    public string[] Roles {get;set;}
    [Description("Page status")]
    public PageStatus PageStatus { get; set; } = PageStatus.Completed;
    [Description("Is parent")]
    public bool IsParent {get;set;}
    [Description("Serial Number")]
    public int SerialNo { get; set; }
    [Description("Menu section")]
    public MenuSectionDto MenuSection { get; set; } = new();

    public List<MenuSectionSubItemDto> MenuItems {get; set;}
}

