//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Defines mapping methods between `Lookup` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting lookup data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Lookups.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.Lookups.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Lookups.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class LookupMapper
{
    public static partial LookupDto ToDto(Domain.Entities.Common.Lookup source);
    public static partial Domain.Entities.Common.Lookup FromDto(LookupDto dto);
    public static partial Domain.Entities.Common.Lookup FromEditCommand(AddEditLookupCommand command);
    public static partial AddEditLookupCommand CloneFromDto(LookupDto dto);
    public static partial AddEditLookupCommand ToEditCommand(LookupDto dto);
    public static partial void ApplyChangesFrom(AddEditLookupCommand source, Domain.Entities.Common.Lookup target);
    public static partial IQueryable<LookupDto> ProjectTo(this IQueryable<Domain.Entities.Common.Lookup> q);
}

