//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       This file defines the command, handler, and associated logic for importing 
//       menusectionsubitems from an Excel file into the CleanArchitecture.Blazor application. 
//       The import process supports validating data and ensuring no duplicates are 
//       inserted. Additionally, a command for creating a menusectionsubitem template file is provided 
//       to facilitate bulk data entry for end users.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/menusectionsubitem
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// - Use `ImportMenuSectionSubItemsCommand` to import menusectionsubitems from an Excel file, ensuring proper validation
//   and avoiding duplicates.
// - Use `CreateMenuSectionSubItemsTemplateCommand` to generate an Excel template for entering menusectionsubitem data 
//   that can be later imported using the import command.

using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Caching;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Commands.Import;

    public class ImportMenuSectionSubItemsCommand: IRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public ImportMenuSectionSubItemsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateMenuSectionSubItemsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportMenuSectionSubItemsCommandHandler : 
                 IRequestHandler<CreateMenuSectionSubItemsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportMenuSectionSubItemsCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        private readonly IStringLocalizer<ImportMenuSectionSubItemsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly MenuSectionSubItemDto _dto = new();

        public ImportMenuSectionSubItemsCommandHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ImportMenuSectionSubItemsCommandHandler> localizer)
        {
            _context = context;
            _localizer = localizer;
            _excelService = excelService;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportMenuSectionSubItemsCommand request, CancellationToken cancellationToken)
        {

           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, MenuSectionSubItemDto, object?>>
            {
                { _localizer[_dto.GetMemberDescription(x=>x.MenuSectionItemId)], (row, item) => item.MenuSectionItemId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.MenuSectionItemId)]]) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Title)], (row, item) => item.Title = row[_localizer[_dto.GetMemberDescription(x=>x.Title)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Href)], (row, item) => item.Href = row[_localizer[_dto.GetMemberDescription(x=>x.Href)]].ToString() }, 
{ _localizer[_dto.GetMemberDescription(x=>x.PageStatus)], (row, item) => item.PageStatus = Enum.Parse<PageStatus>(row[_localizer[_dto.GetMemberDescription(x=>x.PageStatus)]].ToString()) }, 
{ _localizer[_dto.GetMemberDescription(x=>x.Target)], (row, item) => item.Target = row[_localizer[_dto.GetMemberDescription(x=>x.Target)]].ToString() }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await _context.MenuSectionSubItems.AnyAsync(x => x.Title == dto.Title, cancellationToken);
                    if (!exists)
                    {
                        var item = MenuSectionSubItemMapper.FromDto(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new MenuSectionSubItemCreatedEvent(item));
                        await _context.MenuSectionSubItems.AddAsync(item, cancellationToken);
                    }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateMenuSectionSubItemsTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportMenuSectionSubItemsCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.MenuSectionItemId)], 
_localizer[_dto.GetMemberDescription(x=>x.Title)], 
_localizer[_dto.GetMemberDescription(x=>x.Href)], 
_localizer[_dto.GetMemberDescription(x=>x.Target)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

