//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines a query to retrieve a menusectionitem by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same menusectionitem.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Caching;
using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Mappers;
using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Queries.GetById;

public class GetMenuSectionItemByIdQuery : IRequest<Result<MenuSectionItemDto>>
{
   public required int Id { get; set; }
   public string CacheKey => MenuSectionItemCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => MenuSectionItemCacheKey.Tags;
}

public class GetMenuSectionItemByIdQueryHandler :
     IRequestHandler<GetMenuSectionItemByIdQuery, Result<MenuSectionItemDto>>
{
    private readonly IApplicationDbContext _context;

    public GetMenuSectionItemByIdQueryHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<Result<MenuSectionItemDto>> Handle(GetMenuSectionItemByIdQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.MenuSectionItems.ApplySpecification(new MenuSectionItemByIdSpecification(request.Id))
                                                .ProjectTo()
                                                .FirstAsync(cancellationToken);
        return await Result<MenuSectionItemDto>.SuccessAsync(data);
    }
}
