//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       This file defines the command and its handler for deleting one or more
//       MenuSectionSubItem entities from the CleanArchitecture.Blazor application. It
//       implements caching invalidation logic to ensure that data consistency is
//       maintained. Domain events are triggered for deleted entities to support 
//       integration with other parts of the system.
//       for separation of concerns and encapsulation.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/menusectionsubitem
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to delete multiple MenuSectionSubItems from the system by specifying
// their IDs. The handler also raises domain events for each deleted menusectionsubitem to
// notify other bounded contexts and invalidate relevant cache entries.

using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Caching;
using CleanArchitecture.Blazor.Domain.Events.MenuSectionItems;


namespace CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Commands.Delete;

public class DeleteMenuSectionSubItemCommand:  IRequest<Result<int>>
{
  public int[] Id {  get; }
  public DeleteMenuSectionSubItemCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteMenuSectionSubItemCommandHandler : 
             IRequestHandler<DeleteMenuSectionSubItemCommand, Result<int>>

{
    private readonly IApplicationDbContext _context;
    public DeleteMenuSectionSubItemCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(DeleteMenuSectionSubItemCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.MenuSectionSubItems.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new MenuSectionSubItemDeletedEvent(item));
            _context.MenuSectionSubItems.Remove(item);
        }
        var result = await _context.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(result);
    }

}

