//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the MenuSection entity 
//       used within the CleanArchitecture.Blazor application. The MenuSectionDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/menusection
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `MenuSectionDto` class is used to represent menusection data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing menusection information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

using CleanArchitecture.Blazor.Application.Features.MenuSectionItems.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.MenuSections.DTOs;

[Description("MenuSections")]
public class MenuSectionDto
{
    [Description("Id")]
    public int Id { get; set; }
    [Description("Title")]
    public string Title { get; set; } = string.Empty;
    [Description("Roles")]
    public string[] Roles { get; set; }
    [Description("Serial number")]
    public int SerialNo { get; set; }

    public List<MenuSectionItemDto> SectionItems { get; set; }
}

