//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-11
//     Last Modified: 2024-12-11
//     Description: 
//       Defines a query to retrieve all menusectionsubitems from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Mappers;
using CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionSubItems.Queries.GetAll;

public class GetAllMenuSectionSubItemsQuery : IRequest<IEnumerable<MenuSectionSubItemDto>>
{
}

public class GetAllMenuSectionSubItemsQueryHandler :
     IRequestHandler<GetAllMenuSectionSubItemsQuery, IEnumerable<MenuSectionSubItemDto>>
{
    private readonly IApplicationDbContext _context;

    public GetAllMenuSectionSubItemsQueryHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<MenuSectionSubItemDto>> Handle(GetAllMenuSectionSubItemsQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.MenuSectionSubItems.ProjectTo()
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


