//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2024-12-09
//     Last Modified: 2024-12-09
//     Description: 
//       Defines a specification for applying advanced filtering options to the 
//       MenuSectionItem entity, supporting different views and keyword-based searches.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.MenuSectionItems.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for advanced filtering of MenuSectionItems.
/// </summary>
public class MenuSectionItemAdvancedSpecification : Specification<MenuSectionItem>
{
    public MenuSectionItemAdvancedSpecification(MenuSectionItemAdvancedFilter filter)
    {
        DateTime today = DateTime.UtcNow;
        var todayrange = today.GetDateRange(MenuSectionItemListView.TODAY.ToString(), filter.LocalTimezoneOffset);
        var last30daysrange = today.GetDateRange(MenuSectionItemListView.LAST_30_DAYS.ToString(),filter.LocalTimezoneOffset);

        Query.Where(q => q.Title != null)
             .Where(filter.Keyword,!string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CreatedBy == filter.CurrentUser.UserId, filter.ListView == MenuSectionItemListView.My && filter.CurrentUser is not null)
             .Where(x => x.Created >= todayrange.Start && x.Created < todayrange.End.AddDays(1), filter.ListView == MenuSectionItemListView.TODAY)
             .Where(x => x.Created >= last30daysrange.Start, filter.ListView == MenuSectionItemListView.LAST_30_DAYS);
       
    }
}
