//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Defines a query to export lookupdetail data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified lookupdetail details.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.LookupDetails.DTOs;
using CleanArchitecture.Blazor.Application.Features.LookupDetails.Mappers;
using CleanArchitecture.Blazor.Application.Features.LookupDetails.Caching;
using CleanArchitecture.Blazor.Application.Features.LookupDetails.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.LookupDetails.Queries.Export;

public class ExportLookupDetailsQuery : LookupDetailAdvancedFilter, IRequest<Result<byte[]>>
{
      public LookupDetailAdvancedSpecification Specification => new LookupDetailAdvancedSpecification(this);
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
}
    
public class ExportLookupDetailsQueryHandler :
         IRequestHandler<ExportLookupDetailsQuery, Result<byte[]>>
{
        private readonly IApplicationDbContext _context;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportLookupDetailsQueryHandler> _localizer;
        private readonly LookupDetailDto _dto = new();
        public ExportLookupDetailsQueryHandler(
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportLookupDetailsQueryHandler> localizer
            )
        {
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportLookupDetailsQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.LookupDetails.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo()
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<LookupDetailDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                    {_localizer[_dto.GetMemberDescription(x=>x.LookupId)],item => item.LookupId}, 
{_localizer[_dto.GetMemberDescription(x=>x.Code)],item => item.Code}, 
{_localizer[_dto.GetMemberDescription(x=>x.Name)],item => item.Name}, 
{_localizer[_dto.GetMemberDescription(x=>x.NameBN)],item => item.NameBN}, 
{_localizer[_dto.GetMemberDescription(x=>x.Description)],item => item.Description}, 
{_localizer[_dto.GetMemberDescription(x=>x.LookupDetailId)],item => item.LookupDetailId}, 
{_localizer[_dto.GetMemberDescription(x=>x.IsActive)],item => item.IsActive}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
